### ISSUE TITLE
Not able to redirect

### ISSUE THREAD

**Issue by manishoctal** [GabrielBB/react-use-session#1]
I am using this package. 

```
const { session, saveJWT, clear } = useSession('honey-well');
  console.log(session);
  if(!session) {
    return <Redirect to='/login'  />
  }
```

when the route is changed, then redirect not working. Only refresh page redirect to login. any suggestions?

**Comment by GabrielBB** [comment]
Hi, @manishoctal . I recommend using a more hook friendly routing library. I have a condition exactly like yours using [Paratron's Hook Router](https://github.com/Paratron/hookrouter ) and it's working fine. Here you can find how to navigate using that library: [Programmatic navigation](https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/03_navigation.md#programmatic-navigation)

**Comment by GabrielBB** [comment]
Closing issue as it is not related to this library
